name: Ubuntu
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository:  idris-lang/Idris2
          path: idris2
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "::add-path::$HOME/.idris2/bin"
      - name: Build from bootstrap
        run: |
          cd idris2
          make bootstrap && make install
        shell: bash
      - name: Build and test
        run: |
          cd main
          make clean && make build && make install && make test INTERACTIVE=''
        shell: bash
