name: Ubuntu
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: idrall build and test
        run: |
          make clean && make build && make install && make test INTERACTIVE=''
        shell: bash
      - name: Step To run on failure
        if: ${{ failure() }}
        run: |
          cat -vet tests/idrall/idrall001/expected
          cat -vet tests/idrall/idrall001/output
          md5sum tests/idrall/idrall001/expected
          md5sum tests/idrall/idrall001/output
