name: Ubuntu
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: dhall-lang/dhall-lang
          path: dhall-lang
          ref: '12d5a99'
      - name: idrall build and test
        run: |
          make clean && make build && make install && make test INTERACTIVE=''
        shell: bash
